window.CLIPPER_PROJECTS = [
  {
    slug: 'coffee-ritual',
    title: 'Coffee ritual',
    category: 'PRODUCT MONTAGE',
    duration: '0:12',
    sourceLabel: 'Mixkit',
    poster: 'media/coffee-ritual-spec.jpg?v=20260924-2',
    cover: 'media/coffee-ritual-cover.jpg?v=20260924-2',
    coverPosition: '50% 50%',
    coverText: false,
    note: 'Four licensed close-ups cut to an original 120 BPM rhythm.',
    video: 'media/coffee-ritual-spec.mp4?v=20260924-2',
    rights: 'Independent spec edit using four Mixkit Stock Video Free License clips; no client or coffee brand is represented.',
    sourceUrl: 'https://mixkit.co/free-stock-video/coffee/',
    licenseUrl: 'https://mixkit.co/license/modal/videoFree/'
  },
  {
    slug: 'four-systems-one-planet',
    title: 'Four systems, one planet',
    category: 'MOTION STORY',
    duration: '0:20',
    sourceLabel: 'NASA SVS',
    poster: 'media/earth-systems-study.jpg?v=20260924-2',
    cover: 'media/earth-systems-cover.jpg?v=20260924-2',
    coverPosition: '50% 50%',
    coverText: false,
    note: 'Four data chapters recut with original typography and sound design.',
    video: 'media/earth-systems-study.mp4?v=20260924-2',
    rights: 'Independent edit of NASA SVS Earth System Science Spheres visuals. The source audio is not used; NASA does not endorse this edit.',
    sourceUrl: 'https://svs.gsfc.nasa.gov/31365/',
    licenseUrl: 'https://svs.gsfc.nasa.gov/help/'
  },
  {
    slug: 'game-day',
    title: 'Game day',
    category: 'SPORTS HOOK',
    duration: '0:12',
    sourceLabel: 'Mixkit',
    poster: 'media/game-day.jpg?v=20260925-1',
    cover: 'media/game-day-cover.jpg?v=20260925-1',
    coverPosition: '50% 50%',
    coverText: false,
    note: 'Training footage cut into a four-beat pre-match hook.',
    video: 'media/game-day.mp4?v=20260925-1',
    rights: 'Independent spec edit using four Mixkit Stock Video Free License clips; no client, brand or venue is represented.',
    sourceUrl: 'https://mixkit.co/free-stock-video/',
    licenseUrl: 'https://mixkit.co/license/modal/videoFree/'
  },
  {
    slug: 'room-with-a-view',
    title: 'Room with a view',
    category: 'PROPERTY TOUR',
    duration: '0:12',
    sourceLabel: 'Mixkit',
    poster: 'media/room-with-a-view.jpg?v=20260925-1',
    cover: 'media/room-with-a-view-cover.jpg?v=20260925-1',
    coverPosition: '50% 50%',
    coverText: false,
    note: 'A 12-second walkthrough built for a hotel or rental listing.',
    video: 'media/room-with-a-view.mp4?v=20260925-1',
    rights: 'Independent spec edit using four Mixkit Stock Video Free License clips; no client, brand or venue is represented.',
    sourceUrl: 'https://mixkit.co/free-stock-video/',
    licenseUrl: 'https://mixkit.co/license/modal/videoFree/'
  },
  {
    slug: 'after-dark',
    title: 'After dark',
    category: 'TRAVEL / CITY',
    duration: '0:12',
    sourceLabel: 'Mixkit',
    poster: 'media/after-dark.jpg?v=20260925-1',
    cover: 'media/after-dark-cover.jpg?v=20260925-1',
    coverPosition: '50% 50%',
    coverText: false,
    note: 'Night city footage paced for a travel or nightlife opener.',
    video: 'media/after-dark.mp4?v=20260925-1',
    rights: 'Independent spec edit using four Mixkit Stock Video Free License clips; no client, brand or venue is represented.',
    sourceUrl: 'https://mixkit.co/free-stock-video/',
    licenseUrl: 'https://mixkit.co/license/modal/videoFree/'
  },
  {
    slug: 'order-up',
    title: 'Order up',
    category: 'FOOD AD',
    duration: '0:12',
    sourceLabel: 'Mixkit',
    poster: 'media/order-up.jpg?v=20260925-1',
    cover: 'media/order-up-cover.jpg?v=20260925-1',
    coverPosition: '50% 50%',
    coverText: false,
    note: 'Four slow-motion food shots cut as a restaurant menu promo.',
    video: 'media/order-up.mp4?v=20260925-1',
    rights: 'Independent spec edit using four Mixkit Stock Video Free License clips; no client, brand or venue is represented.',
    sourceUrl: 'https://mixkit.co/free-stock-video/',
    licenseUrl: 'https://mixkit.co/license/modal/videoFree/'
  }
];
